spring:
  application:
    name: chat-agent
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  pgvectordatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGV_DB_HOST:localhost}:${PGV_DB_PORT:15432}/${PGV_DB_NAME:postgres}
    username: ${PGV_DB_USERNAME:postgres}
    password: ${PGV_DB_PASSWORD:123456}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 18080

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.transport: DEBUG

